language: node_js
node_js: lts/*
sudo: false
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  on:
    branch: master
  token:
    secure: h2zqcCIt/hIsuvg3Nt8NmSjulVzsq9JoAdz1ndW0DRoWWotcinI3ZKSomTKK0Q4Ko+ETWbtm1g0jQ47sEsS+jpcO3u9CBkz1E58k9M0gE+X0ud26cRToGq3PWkxmplYtsNl6NAMB9+1JuN70Y/vkwifUcexEc6q+IGCORJSrFcMkgsRZNx4E4VgCg6N7KP29NoaWAeQJnaV9pSkbTy1hqQevOdkYfA6c2QOHIcQOCldOdCApGZs4edl19LccpRzmzNCMPes6pAUffdorYyemew85n7c01CClyxOZGNvC/7FtCKdXqk2JaITJSS5c90TU5tivLdqANBhq0KYCLBljDNc2LXPtdz1ETUks6lVmuNvk4DyiGU3wlXA1qKs4oIb+vLRiRzZ73+CCNwnDtWvV+hwWiHOiGDZjroSxVUJo21Q/pAJm1zdC1clq8xDTHkuISWgSMeTnxv6utxoV9NgdIoIiQnKFEW9PslMLxcY3Qerf8SEIu2IiHQs23OrbDUFVDV/7kw+rC05VaHuCov+qtckRmzCqN5wyndVw2zg8ogtOe8Q6oYiqD1bR+xeTP7vKxRgAY2CHQqIFSuqUg51DzGmHMXn6lCM5CLKxdnnV0tnp5lQRiiLfLwwZJ8w6OJJbItx2m3//HWp64N+vc3vjPkP3ReCXiJ0v9yJggUKyeJk=
